
title: 简历
url: 'https://elijah12138.github.io/'
baseurl: '/Elijah3513' #change it according to your repository name



# Profile information
yourname: Elijah
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: 山东，淄博


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
